// HistogramBased_ImageProcessorHandlers.idl : Histogram-Based_ImageProcessorHandlers의 IDL 소스입니다.
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(HistogramBased_ImageProcessorHandlers.tlb) 및 마샬링 코드가 생성됩니다.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(C5CA4206-D97C-4030-96B8-B3BFE3AB8991),
	pointer_default(unique)
]
interface IPreview : IUnknown
{
};

[
	object,
	uuid(5BEF4391-CBBB-4DBF-B035-DBC75465A58A),
	pointer_default(unique)
]
interface IThumbnail : IUnknown
{
};

[
	uuid(34459770-BAD7-4355-868C-2273BC9AAD49),
	version(1.0),
]
library Histogram-Based_ImageProcessorHandlersLib
{
	importlib("stdole2.tlb");
	[
		uuid(621D9E32-26F8-4C0A-B715-96BB1296FC60)
	]
	coclass Preview
	{
		[default] interface IPreviewHandler;
	};
	[
		uuid(EB980FB0-1704-43F1-AE1F-8D717E6C1CF8)
	]
	coclass Thumbnail
	{
		[default] interface IThumbnailProvider;
	};
};

import "shobjidl.idl";
import "thumbcache.idl";
